version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: govango_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: govango_db
      MYSQL_USER: govango_user
      MYSQL_PASSWORD: govango_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - govango_network

networks:
  govango_network:

volumes:
  mysql_data:
